version: '3.7'
services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - ./.env-docker
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  e2e-tests:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - postgres
    command: sh -c "npm run test:e2e"
